Path spec fix (#129)
* focus fix on hamberger menu

* commit path updated

diff --git a/.github/workflows/sync-package-periodically.yml b/.github/workflows/sync-package-periodically.yml
--- a/.github/workflows/sync-package-periodically.yml
+++ b/.github/workflows/sync-package-periodically.yml
@@ -28,9 +28,9 @@ jobs:
         run: |
             git config --local user.email "actions@github.com"
             git config --local user.name "GitHub Actions"
-            git add commit.txt
+            git add scripts/commit.txt
             git commit -m 'Data Updated' ||  echo 'No changes to commit'
-            git push origin || echo "No changes to commit"
+            git push origin || echo "Error While pushing the changes to origin"
             
       - name: Check for differences
         run: |
