reset the validate workflow to original. There should be no changes between runs

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -26,10 +26,8 @@ jobs:
 
       - name: Check for differences
         run: |
-          if git diff --quiet -- . ':!en/package/' ':!output.json'; then
-            echo "No unexpected changes detected."
-          else
-            echo "::error ::Detected unexpected changes outside 'en/package/' directory and in 'output.json'."
+          if ! git diff --quiet; then
+            echo "::error ::Detected changes when regenerating website."
             git diff --stat
             exit 1
           fi
